---
- name: Apply Base Configuration
  hosts: all
  roles:
    - common
    - security_baseline

- name: Setup Docker Hosts
  hosts: docker_hosts
  roles:
    - docker_host

- name: Setup Utility Hosts
  hosts: utility_hosts
  roles:
    - utility_host
